---
- name: Подключение
  community.docker.docker_swarm:
    state: join
    remote_addrs: "{{ docker_swarm_advertise_addr }}"
    join_token: >
      {{
        hostvars['server1']['ansible_facts']['token_worker']
        if type == 'worker' else
        hostvars['server1']['ansible_facts']['token_manager']
      }}