galaxy_info:
  role_name: docker_network_init
  description: Инициализация overlay сети docker
  author: Andrey Polnikov
  license: MIT
  min_ansible_version: 2.9
  platforms:
    - name: Ubuntu
      versions:
        - all