galaxy_info:
  role_name: deploy
  description: Выкладка микросервисов в docker кластер
  author: Andrey Polnikov
  license: MIT
  min_ansible_version: 2.9
  platforms:
    - name: Ubuntu
      versions:
        - all
